### ISSUE TITLE
me eprdi

### ISSUE THREAD

**Issue by Jesicapaz89** [Intercoonecta/proy5-regiones-comparacion#13]
porfi pasame el link d zoom @judithcamps

**Comment by emiliom** [comment]
No quiero poner el link de Zoom aquí, que es un lugar público. Si te vas al foro General de Intercoonecta, y ahí encontrarás el enlace a Zoom.

**Comment by Jesicapaz89** [comment]
ya conseguí entrar! gracias

**Comment by emiliom** [comment]
"Cierro" este issue porque ya está resuelta!
