### ISSUE TITLE
Enrique, ayuda con tu tutorial de extracciones de OBIS por regiones LME?

### ISSUE THREAD

**Issue by emiliom** [Intercoonecta/proy5-regiones-comparacion#7]
Hola Enrique @eqmh! No sé si verás esto a tiempo, mucho menos si tendrás tiemp. Estamos ahorita en el [evento OceanHackWeek en español](https://intercoonecta.github.io/), y una participante (@judithcamps ) en [este proyecto](si alguien pudiera indicarme, gracias) está tratando de correr tu tutorial de agosto del año pasado pero se ha topado con problemas: https://github.com/oceanhackweek/ohw-tutorials/tree/OHW22/optional/espanol/lme-obis-extracciones

Copio aquí parte de su reporte de error. Creés que nos podrías ayudar hoy o mañana jueves?

> Durante el transcurso de la semana he intentado extraer información de OBIS con R, pero he tenido problemas dado que el paquete "rgdal" está en desuso. He podido solucionar muchos pasos con "sp" o "terra". Aún así me he encontrado con este problema: 

```r
geom_path(data = dat.sel_5, + aes(x = long, y = lat, group = group), + colour = "chartreuse4", size = 1, inherit.aes = FALSE) + + geom_path(data = dat.sel_4, + aes(x = long, y = lat, group = group), + colour = "coral", size = 0.75, inherit.aes = FALSE)

> p.sel

Error in `geom_path()`: ! Problem while computing aesthetics. ℹ Error occurred in the 1st layer. Caused by error in `FUN()`: ! object 'group' not found Run `rlang::last_error()` to see where the error occurred. > rlang::last_error() <error/rlang_error> Error in `geom_path()`: ! Problem while computing aesthetics. ℹ Error occurred in the 1st layer. Caused by error in `FUN()`: ! object 'group' not found --- Backtrace: 1. base (local) `<fn>`(x) 2. ggplot2:::print.ggplot(x) 4. ggplot2:::ggplot_build.ggplot(x) 5. ggplot2:::by_layer(...) 12. ggplot2 (local) f(l = layers[[i]], d = data[[i]]) 13. l$compute_aesthetics(d, plot) 14. ggplot2 (local) compute_aesthetics(..., self = self) 15. ggplot2:::scales_add_defaults(...) 16. base::lapply(aesthetics[new_aesthetics], eval_tidy, data = data)

17. rlang (local) FUN(X[[i]], ...) Run `rlang::last_trace()` to see the full context.
```

**Comment by emiliom** [comment]
@judithcamps viendo de nuevo el error y el código original, veo que donde ocurre error no es vital para la extracción de datos. Parece ser simplemente una visualización en mapa de los LMEs. Pareciera que podrías omitirlo por ahora y seguir con la parte del código que realmente utiliza `robis`. Has probado hacer eso?

**Comment by judithcamps** [comment]
Ahora he provado y si puedo seguir avanzando, pero es una pena que no pueda graficarlo. Además, aprovecho para preguntar cómo sería extraer esa información por ecoregiones. En el vídeo enrique comenta que esto está por grandes regiones marinas pero que hay una forma de hacerlo por ecoregiones pero no encuentro cómo.

**Comment by emiliom** [comment]
Que bueno @judithcamps ! Ya buscaremos ayuda para poder graficar los mapas.

Has buscado en la documentación de `robis`, acerca de busqueda por ecoregion? En una vista rapida, parece que por lo menos permite pasar una geometría como argumento de búsqueda. Talvez podrías usar esa estrategia, usando la geometría del polígono de una ecoregion.

**Comment by emiliom** [comment]
@judithcamps tal parece que las áreas disponibles en robis (y obis.org) se puede inspeccionar con la función `area()` de robis: https://iobis.github.io/robis/reference/area.html. Pero también ya confirmé que las ecoregiones MEOW no son una de las regiones disponibles, así que no nos ayudará.

**Comment by marianpena** [comment]
Hola, 
No tengo claro si estais usando el mismo dataset que el tutorial (LMEs66) o el de vuestra carpetas (meow_ecos)

**Comment by marianpena** [comment]
Ah ok veo que no usas readOGR que a mi me daba error (el de MEOW lo lee bien sin embargo y crea la variable group). la función st_read de sf parece que funciona diferente y no te crea esa variable group. A mi me da error ; dice q el fichero está corrupto :S

**Comment by judithcamps** [comment]
y con MEOW crea un mapa con ecoregiones? A mi me gustaría que la información que saco por cada ecoregion se repreente en un mapa con la delimitación de estas áreas, pero no lo consigo. Solo la extracción de observaciones

**Comment by marianpena** [comment]
creo que lo que te falta a ti es cambiar el nombre de las variables x e y como te dije; no tienes long pero me parecio q tenias x e y...probaste eso?

**Comment by marianpena** [comment]
Me sale esto con MEOW
![image](https://user-images.githubusercontent.com/1233089/222435146-5718f402-7cf5-4003-8406-f9ef69dfc05c.png)

**Comment by marianpena** [comment]
Y sin los limites
![image](https://user-images.githubusercontent.com/1233089/222435790-a26c7d4b-2212-4788-9e8f-a2d4120b2d3b.png)

**Comment by judithcamps** [comment]
Súper, gracias!!! Lo pruebo a ver y también ahora después provare lo de cambiar x y y. Igualmente al sacar los datos, estos no los representa como puntos encima de este mapa. Tengo que averiguar cómo hacerlo.

**Comment by judithcamps** [comment]
Con @Jesicapaz89 ya lo conseguimos 

![Guayaquil_ecoregion_diversity2](https://user-images.githubusercontent.com/124306158/222487225-3c49de88-8296-4ccd-a485-3a6b4e92b094.png)

**Comment by emiliom** [comment]
Voy a cerrar este issue. El propósito original de talvez buscar ayuda de Enrique, ya no es necesario.
