### ISSUE TITLE
Día 3 

### ISSUE THREAD

**Issue by Cotsikayala** [Intercoonecta/proy5-regiones-comparacion#8]
Bases de datos SeaWiFS y MODIS del 2000 a la fecha. Son compuestos mensuales 
Seleccionar el intervalo 2000 al 2008 y mapear el área que los compañeros selecciones para la información de diversidad.

file:///C:/Users/Nicolas%20Nickifor/Downloads/D%C3%ADa%201Hachaton.html

**Comment by emiliom** [comment]
Ya subí mi cuaderno jupyter al repositorio, https://github.com/Intercoonecta/proy5-regiones-comparacion/tree/main/emilio

**Comment by judithcamps** [comment]
@Cotsikayala Cotsii podrías subir todo lo que hiciste para clorofila? O lo subiste y no lo encuentro :(

**Comment by emiliom** [comment]
Este issue ya se puede cerrar, ya que no hay nada pendiente ni información útil que mantener visible
